// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTI12IopLkQ55T1LwcX6-mfg_u2Ujfn8Y',
    appId: '1:505007039953:web:6a901a7dff92a213d3ecf0',
    messagingSenderId: '505007039953',
    projectId: 'fir-kibakuss',
    authDomain: 'fir-kibakuss.firebaseapp.com',
    storageBucket: 'fir-kibakuss.appspot.com',
    measurementId: 'G-M3QQ7D7YXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyrQr4RpGaEe7PuPWzeNZTcPIZvtqvz4',
    appId: '1:505007039953:android:a621e23b76a5b453d3ecf0',
    messagingSenderId: '505007039953',
    projectId: 'fir-kibakuss',
    storageBucket: 'fir-kibakuss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnmIQaxfGPb04jMBDMQJvnGaDgG4NLMg',
    appId: '1:505007039953:ios:063a589f229dbf02d3ecf0',
    messagingSenderId: '505007039953',
    projectId: 'fir-kibakuss',
    storageBucket: 'fir-kibakuss.appspot.com',
    iosClientId: '505007039953-jglfh7a63v0dailo8icsrp13pt6mf0ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnmIQaxfGPb04jMBDMQJvnGaDgG4NLMg',
    appId: '1:505007039953:ios:e0a9b164dd895ca1d3ecf0',
    messagingSenderId: '505007039953',
    projectId: 'fir-kibakuss',
    storageBucket: 'fir-kibakuss.appspot.com',
    iosClientId: '505007039953-c5bk8446merk4g4cs3jrtnpkfhd29e0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
